<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      const p1 = new Promise((resolve, reject) => {
        resolve('hello')
      })
        .then((result) => result)
        .catch((e) => e)

      const p2 = new Promise((resolve, reject) => {
        throw new Error('报错了')
      })
        .then((result) => result)
        .catch((e) => e)

      // 其中有一个实例为reject，则将第一个rejecte的返回值传递给回调函数
      // 此处p2有自己的catch方法，执行完毕后变为resolve，导致Promise中的两个参数均为resolve，
      Promise.all([p1, p2]).then(result => console.log(result)).catch(e => console.log(e))      
    </script>
  </body>
</html>
